### ISSUE TITLE
Check what happens when using an "incorrect" locale

### ISSUE THREAD

**Issue by dianabarsan** [medic/angular10-migration#114]
See: https://github.com/medic/cht-core/issues/5705

We've already regressed this issue in 3.8 (see https://medic.slack.com/archives/C02LFG69T/p1610714420014400?thread_ts=1610638866.001800&cid=C02LFG69T)

Make sure that we can support locales of any code.

**Comment by latin-panda** [comment]
Blocked by: https://github.com/medic/angular10-migration/issues/118

**Comment by mrsarm** [comment]
@dianabarsan  I tried to follow what you did [here](https://github.com/medic/cht-core/issues/5705), that is basically what it says in the [community guide](https://docs.communityhealthtoolkit.org/core/overview/translations/#adding-new-languages) of how to add a new language, but I couldn't make the language visible in the login page or in the user settings, so I'm not able to test what is required. This is what I did so far:

1. Go to my CHT local instalation `cd /path/to/my/cht-core`
2. Create the new language file with `cp ddocs/medic/_attachments/translations/messages-en.properties ddocs/medic/_attachments/translations/messages-rn.properties`
3. Add the new language to the list of languages:
   - `vi api/src/translations.js`
   - Add `rn: 'Rare lang (NotExistActually)'` entry to the `LOCAL_NAME_MAP` object.
4. Run `grunt` (fresh database, with no previous config)
5. Run API and sentinel
6. Deploy configurations: `cd config/default/ && medic-conf --local`

After :point_up: , when I go to the login page or the user settings I don't see the new language among all the languages.

What step am I missing?

**Comment by dianabarsan** [comment]
@mrsarm 

The steps you listed are correct, except you don't necessarily need (6) - the default config is enabled automatically for deployments on fresh databases. I followed your steps, just to check, on both master and the migration branch and, as expected, my language did appear in the login list and in the language switcher in the app. 
I suggest you clear your browser cache (service worker cache) or try your login in incognito mode. 

You can also add new languages to a running instance from the admin app or just pushing the translations doc to the db directly.

**Comment by mrsarm** [comment]
Clearing browser cache didn't solve the issue, so I continue the tests adding the language from the UI as you suggested. I made some tests and it worked as expected, languages works fine.

I notice just one difference against master version, that actually may be more like a desired behavior than a bug (so a bug from master that will be fixed by this version):

1. In the login page, choose any language eg. "Bambara".
2. Login
3. Change the language of the user to any language eg English (works OK in both branch)
4. Change again the language to the new language.

Master version: see the text not translated because the new lang does not have translations yet (so the key of the text will displayed instead of a translated version, though most keys are the English version of the text)
Angular 10 branch: the last language chosen from the login is used instead.

**Comment by dianabarsan** [comment]
Thanks for the feedback, @mrsarm !
