### ISSUE TITLE
Flacky e2e: tests/e2e/create-meta-db.js

### ISSUE THREAD

**Issue by latin-panda** [medic/angular10-migration#147]
<img width="716" alt="Screen Shot 2021-02-16 at 1 11 11 pm" src="https://user-images.githubusercontent.com/66472237/108025211-ac97e200-7058-11eb-9a54-f66444a52e7d.png">

https://github.com/medic/cht-core/pull/6930/checks?check_run_id=1908243240

**Comment by dianabarsan** [comment]
I can't replicate this. 
Looking at the build artifact, it looks like "instance" was logged out - the screenshot associated with the failure shows the login page - so it would have been impossible for the browser to show the admin add user screen. 

Because another test that requires login/logouts failed before (the token login ones), I'm curious whether that failure prevented the admin user from being logged back in.

**Comment by dianabarsan** [comment]
I'm marking this as "done" and we can return it if someone sees this fail by itself (without other failures) in the same way.

**Comment by dianabarsan** [comment]
This should be fixed by https://github.com/medic/cht-core/pull/6959
