### ISSUE TITLE
Flacky e2e: tests/e2e/registration-by-sms.js

### ISSUE THREAD

**Issue by latin-panda** [medic/angular10-migration#148]
<img width="782" alt="Screen Shot 2021-02-16 at 1 11 17 pm" src="https://user-images.githubusercontent.com/66472237/108025596-52e3e780-7059-11eb-8a75-87cdda705274.png">

https://github.com/medic/cht-core/pull/6930/checks?check_run_id=1908243240

**Comment by dianabarsan** [comment]
I've figured out why this test failed. 

On the branch where it failed, some tests were shuffled around, so that the test that ran right before this one are the add user tests, which are all in the admin app. 
The problem is that those tests don't redirect back to webapp when they're done, so this test was just sitting there, in the admin app, and waiting for stuff to happen.
